# Keep distinct from zsh history so they don't corrupt one another.
export HISTFILE=~/.bash_history

export SHELL="bash"

# I prefer to use zsh when available
if [[ ! "$TERM" = "dumb" && ! "$TERM" = "" ]]
then
    if which zsh &> /dev/null
    then
				exec zsh
    fi
fi

