#source /etc/profile

source $HOME/etc/shell/path_setup

# note must symlink .profile -> .bash_profile, b/c tramp ignores .bash_profile for reasons unknown.
# only by having both files contain this code do you get seamless login experience w/ both terimnal and tramp shells

# emacsclient needs this set.
# https://askubuntu.com/questions/538416/how-to-set-xdg-runtime-dir
export XDG_RUNTIME_DIR="/run/user/$(id -u)"

if [ -f "$HOME/.cargo/env" ]; then
   source "$HOME/.cargo/env"
fi

if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

