#!/bin/sh

. `dirname $0`/util

# Load OS specific preferences
if [[ -a `dirname $0`/$(uname -s) ]]; then
    . `dirname $0`/$(uname -s)
else
    echo "No shell preferences found for this OS!" >&2
fi

export ANDROID_PATH=~/opt/android-sdk-linux_x86-1.6_r1;
if [[ -d $ANDROID_PATH ]]; then
	path_prepend $ANDROID_PATH/tools
fi

if [[ -d /home/udesktop178/joeg/opt/bin ]]; then
	path_prepend /home/udesktop178/joeg/opt/bin
fi

if [[ -d $HOME/opt/bin ]]; then
	path_prepend $HOME/opt/bin
fi

if [ -d $HOME/opt/lib/python2.6/site-packages ]; then
    export PYTHONPATH=$HOME/opt/lib/python2.6/site-packages:$PYTHONPATH
fi

# Ack is a nice replacement for grep, just does the right thing
# Really should be able to add to the existing make type, but will make mk a separate
# type for now.
ack()
{
	~/etc/bin/ack \
		--type-set incl=.incl \
		--type-set tc=.tc --sort-files \
		--type-set mk=.mk \
		--type-set bejunk=.ii,.utii,.P --type=nobejunk \
		--type-set pagedisplay=.page \
		--type-add hh=.ipp $@;
}

export BROWSER="$ZDOTDIR/etc/bin/launch-my-browser"

# Newer versions of emacs will autoload emacs if ALTERNATE_EDITOR is empty.
export EDITOR="$ZDOTDIR/etc/bin/launch-emacs"

if which htop > /dev/null; then
    alias top='htop'
fi

if grep --version 2> /dev/null | grep GNU &> /dev/null
then
    alias grep='grep --color=auto'
fi

if ls --version 2> /dev/null | grep GNU &> /dev/null
then
    alias ls='ls -F -h --color=auto --group-directories-first'
fi

# Obey my typos!
alias -r sl=ls

# Don't clear the screen when less exits
alias less='less -X'

alias ipython="ipython -colors Linux -noconfirm_exit -nobanner"

# Harmless over LAN on modern CPUs, and very useful when logged into london.
alias ssh="ssh -C -X"

# almost never use mv to overwrite
alias mv="mv -i"

# 99% of the time I want truss to include child processes
file_name=$0

if which truss &> /dev/null; then
    truss()
    {
        echo "Running truss including children. See $file_name."
        disable -f truss
        truss -f $@
        enable -f truss
    }
fi

# Without this OO looks terrible under xmonad
OOO_FORCE_DESKTOP=gnome

# Load tradelink preference
if [[ -d /opt/tradelink ]]; then
    . `dirname $0`/tlsh
else
    test_for_vpn=$(ping -c1 -w2 udesktop178.wacker.trdlnk.com | grep "0 recei")
    if [ "$test_for_vpn" = "" ]; then
	if [ "$(ls -A $HOME/remote/udesktop178)" = "" ]; then
	    sshfs udesktop178.wacker.trdlnk.com:/ $HOME/remote/udesktop178 -o reconnect &
	fi
    fi
fi

if [[ "$(basename $ZDOTDIR)" = "$LOGNAME" ]];
then
    # Although we haven't added $HOME/etc/bin to our path yet,
    # if we're a subshell we may inherit it. We want to remove
    # it temporarily because we're going to find the 'real'
    # locations of different utilities.
    export PATH=$(echo $PATH | sed s,$HOME/etc/bin,,g | sed s,$HOME/etc/bin/$(uname -s),,g)

    if [[ ! -a $HOME/etc/real_locations/$(hostname) ]]; then
        mkdir $HOME/etc/real_locations/$(hostname)
    fi

    which gdb > $HOME/etc/real_locations/$(hostname)/gdb
    which svcadm > $HOME/etc/real_locations/$(hostname)/svcadm
    which tlmake > $HOME/etc/real_locations/$(hostname)/tlmake

    # OK, now put it back in.
    if [[ -d $ZDOTDIR/etc/bin ]]; then
	    path_prepend $ZDOTDIR/etc/bin
	    path_prepend $ZDOTDIR/etc/bin/$(uname -s)
    fi
fi

