#!/usr/bin/env zsh

setup_symlink()
{
    if [[ -a $1 ]]; then
        ln -sf $1 -T $2
    fi
}

setup_symlink $HOME/etc/shell/zshrc $HOME/.zshrc
setup_symlink $HOME/etc/shell/bashrc $HOME/.bashrc

# SuSE insists on there being a fonts directory.
mkdir -p $HOME/.fonts
setup_symlink $HOME/etc/fonts $HOME/.fonts/my-fonts

setup_symlink $HOME/etc/gdbinit $HOME/.gdbinit
setup_symlink $HOME/etc/emacs/emacsrc.el $HOME/.emacs
setup_symlink $HOME/etc/xmonad $HOME/.xmonad
