#!/usr/bin/env zsh

. `dirname $0`/util

setup_symlink $HOME/etc/shell/zshrc $HOME/.zshrc
setup_symlink $HOME/etc/shell/kshrc $HOME/.kshrc
setup_symlink $HOME/etc/shell/bashrc $HOME/.bashrc
setup_symlink $HOME/etc/screenrc $HOME/.screenrc

# SuSE insists on there being a fonts directory.
mkdir -p $HOME/.fonts
setup_symlink $HOME/etc/fonts $HOME/.fonts/my-fonts

setup_symlink $HOME/etc/gdb/gdbinit $HOME/.gdbinit
setup_symlink $HOME/etc/emacs/emacsrc.el $HOME/.emacs
setup_symlink $HOME/etc/xmonad $HOME/.xmonad

# Works on earlier Ubuntu versions
xmonad_path=$(which xmonad)
if [ ! "$xmonad_path" = "" ]; then
    echo "export WINDOW_MANAGER=$xmonad_path" >> $HOME/.gnomerc
fi

# Works on Lucid Lynx, probably not for later Unity based versions.
if which gconftool-2 &> /dev/null; then
    if which xmonad &> /dev/null; then
	gconftool-2 -s /desktop/gnome/session/required_components/windowmanager xmonad --type string
    fi
fi

if which git &> /dev/null; then
	# Make git only push the current branch
	git config --global push.default=current
fi
