#!/bin/sh

########################################
##### script utility functions     #####
########################################

if test `uname -s` = "Linux"
then
	ps_crossplatform()
	{
		ps aux;
	}
fi

if test `uname -s` = "SunOS"
then
	ps_crossplatform()
	{
		ps -ef;
	}
fi

tsk()
{
 	# We filter out grep from the list of processes so
	# long as grep isn't the process we're actually trying
	# to see running
	if expr match $1 "grep"
	then
		ps_crossplatform | grep -i $@;
	else
		ps_crossplatform | grep -i $@ | grep -v grep;
	fi
}

error()
{
	if test -n "$DISPLAY"
	then
		if which xmessage > /dev/null;
		then
			xmessage "Error: " $@ > /dev/null;
			return 0;
		fi
	else
		echo "Error: " $@ >&2;
	fi
}

is_symlink()
{
	if test -e $1
	then
		if test -L $1
		then
			echo -n '' > /dev/null;
		else
			error "$1 isn't a symlink.";
			return 1;
		fi
	fi

	return 0;
}

try_apps()
{
	for app in "$@"
	do
		app_no_opts="$(echo $app | cut -d ' ' -f 1)";
		if which $app_no_opts > /dev/null;
		then
			eval "$app";
			if test "$?" = "130" -o "$?" = "0" # SIGINT is OK
			then
				break;
			else
				if test "$app" = "$1";
				then
					error "Nonzero exit code from:" $app;
				fi
			fi
		else
			if test "$app" = "$1";
			then
				error "Could not find:" $1;
			fi
		fi
	done
}

# Tries harder and harder to kill a process,
# but starts the nice way.
nice_kill()
{
	to_kill=$1

	for sig in INT TERM KILL
	do
		echo "Trying SIG$sig on $to_kill"
		kill -$sig $to_kill
		if (! ps $to_kill );
		then
			echo "Killed successfully."
			return 0;
		fi
		sleep 1;
	done

	echo "Could not kill!"
	return 1;
}

# Supports a second parameter to filter out things
# to NOT kill. useful for killing 'x' before running
# 'launch-x'
nice_pkill()
{
	echo "Killing" \'$1\' "processes that don't contain" \'$2\';

	if test $# -eq 1
	then
		filter() { cat; }
	elif test $# -eq 2
	then
		filter() { grep -v $1; }
	else
		echo "Error, too many parameters.";
		return 1;
	fi

	seek() { pgrep -l $1 | filter $2 | awk '{ print $1 }'; }

	to_kill=$(seek $1 $2);

	if test "$to_kill" != ""
	then
		nice_kill $to_kill;
	fi
}
