#!/bin/sh

PREFERRED_EMACS=emacs
PREFERRED_EMACSCLIENT=emacsclient
if which emacs-snapshot-gtk > /dev/null
then
	PREFERRED_EMACS=emacs-snapshot-gtk
	PREFERRED_EMACSCLIENT=emacsclient.emacs-snapshot
fi

# Weird hack needed to make things work on goat
if test "$DISPLAY" != ":0.0"
then
	EMACS_DISPLAY=""
else
	EMACS_DISPLAY=$DISPLAY
fi
