# prefix key that doesn't conflict with emacs, and is still easy to
# press on ours keyboard for termux
unbind C-b
set -g prefix C-z
bind C-z send-prefix

set -g mouse on
bind r source-file ~/.tmux.conf \; display-message "config reloaded"

set -g history-limit 100000

# tmux waits 500ms after Esc to see if it's the start of a function-key sequence,
# this makes it feel laggy
set -sg escape-time 10

# some programs like to know when they gain/lose focus
set -g focus-events on

# settings needed for shift+enter to work in agent interfaces
# bind-key -n S-Enter send-keys Escape "[13;2u"
set -g allow-passthrough on
set -s extended-keys always
set -as terminal-features '*:extkeys'
