#!/bin/sh

browser_list="chromium-browser google-chrome firefox4 firefox3 firefox epiphany mozilla"

# -n means "name only", we remove the path and any digits
if test "$1" = "-n"; then
    temp=`$HOME/etc/utils/pick_best $browser_list`
    echo `basename $temp | tr -d 1234567890`
else
    $HOME/etc/utils/pick_best $browser_list
fi

