#!/usr/bin/env zsh

browser_list="google-chrome google-chrome-stable chromium-browser firefox"

# -n means "name only", we remove the path and any digits
if test "$1" = "-n"; then
    temp=`$HOME/etc/utils/pick_best $browser_list`
    echo `basename $temp | tr -d 1234567890`
else
    $HOME/etc/utils/pick_best $browser_list
fi

