#!/bin/sh

set -u;
set -e;

. $HOME/etc/shell/util

uninstall_xmonad()
{
	echo "Uninstalling xmonad preferences..."
	if is_symlink $HOME/.xmonad/xmonad.hs
	then
		rm -r $HOME/.xmonad
	fi
	echo "Uninstalled xmonad preferences successfully"
}

install_xmonad()
{
	echo "Installing xmonad preferences..."
	if test -e $HOME/.xmonad
	then
		error "xmonad was not torn down cleanly!"
		uninstall_xmonad
	fi

	mkdir $HOME/.xmonad
	ln -s $HOME/etc/xmonad/xmonad.hs $HOME/.xmonad/xmonad.hs

	echo "Installed xmonad preferences successfully."
}

kill_wms()
{
	echo "Killing existing window managers..."
	for wm in $@
	do
		wm_no_opts=$(echo "$wm" | cut -d ' ' -f 1)
		nice_pkill $wm_no_opts launch; true;
	done
	echo "Killed existing window managers successfully..."
}

echo "Starting with pid $$"
export MAIN_SCRIPT_PID=$$

install_xmonad

# kill other instances of the script
nice_pkill launch-xmonad

# Try to keep a functioning window manager even if xmonad fails
IFS=$'@' WM_LIST="xmonad@metacity --replace@kwin --replace@sawfish@openbox@twm";
IFS=$'@' kill_wms $WM_LIST;

trap "uninstall_xmonad; exit" EXIT
set +e;
IFS=$'@' try_apps $WM_LIST;
set -e;

