(md-make-snippets
 '(derived-mode-p 'rust-mode)
 '(
   ("function" "fn $1($2) -> $3 {\n    $4\n}")
   ("main" "fn main() {\n    $1\n}")
   ("print" "println!($1);")
   ("if" "if $1 {\n    $2\n}")
   ("else" "else {\n    $2\n}")
   ("flat if" "if $1 { $2 } else { $3 }")
   ("let" "let $1 = $2;")
   ("const" "const $1 = $2;")
   ("let mutt" "let mut $1 = $2;")
   ("loop" "loop {\n    $1\n}")
   ("while" "while $1 {\n    $2\n}")
   ("for" "for $1 in $2 {\n    $3\n}")
   ("annotate" "$1: $2")
   ("and" "$1 && $2")
   ("or" "$1 || $2")
   ("assign" "$1 = $2;")
   ("comment" "// $1")
))
