(md-make-snippets
 '(derived-mode-p 'rust-mode)
 '(
   ("new" "$1::new($2)")
   ("default" "$1::default()")
   ("stood" "std::$1")
   ("option" "Option<$1>")
   ("box" "Box<$1>")
   ("assert" "assert!($1)")
   ("iter" "$1.iter()")
   ("collect" "$1.collect()")
   ("map" "$1.map($2)")
   ("assert equal" "assert_eq!($1, $2)")
   ("module" "mod $1 {\n    $2\n}")
   ("function" "fn $1($2) -> $3 {\n    $4\n}")
   ("main" "fn main() {\n    $1\n}")
   ("into" "$1.into()")
   ("print" "println!($1);")
   ("return" "return $1;")
   ("if" "if $1 {\n    $2\n}")
   ("if let" "if let $1 = $2 {\n    $3\n}")
   ("struct" "struct $1 {\n    $2\n}")
   ("enum" "enum $1 {\n    $2\n}")
   ("else" "else {\n    $2\n}")
   ("flat if" "if $1 { $2 } else { $3 }")
   ("let" "let $1 = $2;")
   ("const" "const $1 = $2;")
   ("let mutt" "let mut $1 = $2;")
   ("loop" "loop {\n    $1\n}")
   ("while" "while $1 {\n    $2\n}")
   ("for" "for $1 in $2 {\n    $3\n}")
   ("annotate" "$1: $2")
   ("and" "$1 && $2")
   ("or" "$1 || $2")
   ("trait" "trait $1 {\n    $2\n}")
   ("Imphal" "impl $1 {\n    $2\n}")
   ("assign" "$1 = $2;")
   ("comment" "// $1")
   ("todo" "// TODO: $1")
   ("as" "$1 as $2")
   ("derive" "#[derive($1)]")
   ("use" "use $1::$2;")
   ("format" "format!($1)")
   ("match" "match $1 {\n    $2 => $3,\n    _ => $4\n}")
   ("unwrap" "$1.unwrap()")
   ("self" "self.$1")
   ("clone" "$1.clone()")
   ("debug" "dbg!($1)")
   ("equals" "$1 == $2")
   ("not equal" "$1 != $2")
   ("trace" "dbg!();")
   ("size" "$1.size()")
   ("macro rules" "macro_rules! $1 {\n    ($2) => $3\n}")
   ("thread local" "thread_local! {\n    $1\n}")
   ("cell" "Cell<$1>")
   ("ref cell" "RefCell<$1>")
   ("R C" "Rc<$1>")
   ("arc" "Arc<$1>")
   ("vec" "Vec<$1>")
   ("type" "type $1 = $2")
   ("stringify" "stringify!($1)")
   ("mutex" "Mutex<$1>")
   ("weak" "Weak<$1>")
   ("result" "Result<$1, $2>")
   ("quote" "quote! {\n    $1\n}")
   ("read" "$1.read()")
   ("write" "$1.write()")
))
