(md-make-snippets
 '(derived-mode-p 'sh-mode 'shell-mode 'eshell-mode)
 '(
   ("said" "sed 's/$1/$2/g' $3")
   ("tee" "tee $1")
   ("grep" "grep \"$1\"")
   ("line count" "wc -l")
   ("move" "mv $1 $2")
   ("copy" "cp $1 $2")
   ("see D" "cd $1")
   ("GDB" "gdb --args $1")
   ("diff" "diff -u $1 $2")
   ("man" "man $1")
   ("help" "$1 --help")
   ("apt get install" "apt-get install $1")
   ("apt cache search" "apt-cache search $1")
   ("pea S" "ps -ef | grep $1")
   ("echo" "echo $1")
   ("make dir" "mkdir -p $1")
   ("L D library path" "LD_LIBRARY_PATH=$1")
   ("S S H" "ssh $1")
   ("find" "find . -name \"*$1*\"")
   ("sleep" "sleep $1")
   ("cut" "cut -d' ' -f$1")
   ("bash" "bash -c \"$1\"")
   ("sudo" "sudo $1")
   ))
