(md-make-snippets
 '(derived-mode-p 'sh-mode 'shell-mode)
 '(
   ("if" "if [ $1 ]; then\n    $2\nfi")
   ("said" "sed 's/$1/$2/g' $3")
   ("tee" "tee $1")
   ("grep" "grep \"$1\"")
   ("stood out" "$1 > $2")
   ("stood err" "$1 2> $2")
   ("stood both" "$1 &> $2")
   ("line count" "wc -l")
   ("move" "mv $1 $2")
   ("copy" "cp $1 $2")
   ("CD", "cd $1")
   ))
