(md-make-snippets
 '(derived-mode-p 'vhdl-mode)
 '(
   ("entity" "entity $1 is port (\n    $2 : $3);\nend entity $1;")
   ("architecture" "architecture $1 of $2 is\n    $3 : $5;\nbegin\n    $6\nend architecture $1;")
   ("signal assign" "$1 <= $2")
   ("var assign" "$1 := $2")
   ("item" "$1 : $2")
   ("down to" "$1 downto $2")
   ("to" "$1 to $2")
   ("with" "with $1 select\n    $3")
   ("std_logic_vector" "std_logic_vector($1)")
   ("unsigned" "unsigned($1)")
   ("band" "$1 | $2")
   ("process"  "process($1)\nbegin\n    $2\nend process;")
   ("if" "if ($1) then\n    $2;\nend if;")
   ("equals" "$1 = $2")
   ("case" "case $1 is\n    when $2 => $3;\n    when others => $4;\nend case;")
))
