(md-make-snippets
 '(derived-mode-p 'verilog-mode)
 '(
   ("assign" "assign $1 = $2;")
   ("wire" "wire $1;")
   ("reg" "reg $1;")
   ("input" "input $1;")
   ("output" "output $1;")
   ("inout" "inout $1;")
   ("module" "module $1($2);\n    $3;\nendmodule")
   ("if" "if ($1) begin\n    $2;\nend")
   ("else" "else ($1) begin\n    $2;\nend")
   ("slice" "[$1:$2]")
   ("binary" "$1'b$2")
   ("octal" "$1'a$2")
   ("hex" "$1'h$2")
   ("decimal" "$1'd$2")
   ("ternary" "($1) ? $2 : $3")
   ("always" "always @($1) begin\n    $2;\nend")
   ("repeat" "repeat ($1) begin\n    $2;\nend")
   ("case" "case ($1)\n    $2: $3;\n    default: $4;\nendcase")
   ("signal assign" "$1 <= $2;")
   ("equals" "$1 == $2")
   ("forever" "forever begin\n    $1;\nend")
   ("initial" "initial begin\n    $1;\nend")
   ("comment" "// $1")
   ("begin" "begin\n    $1;\nend")
   ("flat begin" "begin $1; end")
))
