(defun etc-perl6-mode-hook ()
  (subword-mode 1)
  (setq c-hungry-delete-key t)
  (local-set-key (kbd "C-d") 'c-hungry-delete-forward)
  (local-set-key (kbd "<delete>") 'c-hungry-delete-forward)
  (local-set-key (kbd "<backspace>") 'c-hungry-delete-backwards)
  (setq indent-tabs-mode nil)
  (etc-set-indent-preference 4))

(add-hook 'perl6-mode-hook #'etc-perl6-mode-hook)